name: bogorstore
version: 1.0.0+1
publish_to: none
description: Application PPOB Powered by Bogorstore.2023-06-28-11-00-02.png
environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.5.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
