name: bogorstore
version: 1.0.0+1
publish_to: none
description: Application PPOB Powered by Bogorstore
environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  font_awesome_flutter: ^10.5.0
  http: 1.1.2
  lottie: 2.7.0
  get_storage: 2.1.1
  just_audio: 0.9.36
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
    - assets/icons/
    - assets/images/
    - assets/lotties/
  uses-material-design: true

